# JDBC DataSource Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/spring_student
spring.datasource.username=root
spring.datasource.password=ROOT@123

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# \uD83D\uDD25 TEMPORARY TEACHER LOGIN HACK (BINA CODE KO HAATH LAGAYE)
spring.security.user.name=Manish
spring.security.user.password=123456
spring.security.user.roles=TEACHER