# JDBC DataSource Configuration (Aiven Free Cloud Database)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://mysql-2671ef64-dev974437-8d56.d.aivencloud.com:12339/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_btHrgbAXKbSiLCBjAg2

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# \uD83D\uDD25 TEMPORARY TEACHER LOGIN HACK (BINA CODE KO HAATH LAGAYE)
spring.security.user.name=Manish
spring.security.user.password=123456
spring.security.user.roles=TEACHER